
/**
 * Build Information
 * Format: YYYY.MM.DD.X (Date + Build Count)
 * 
 * This file is automatically generated by scripts/generate-build-number.ts
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next build
 */

export const BUILD_INFO = {
  version: '2025.11.26.14',
  date: 'November 26, 2025',
  description: 'Automatic build 2025.11.26.14'
} as const;

export function getBuildVersion(): string {
  return BUILD_INFO.version;
}

export function getFormattedBuildInfo(): string {
  return `Build ${BUILD_INFO.version}`;
}
