/**
 * Automatic Build Number Generator
 * 
 * Generates build numbers in the format YYYY.MM.DD.X
 * - YYYY: Current year
 * - MM: Current month (zero-padded)
 * - DD: Current day (zero-padded)
 * - X: Build count for the current day
 * 
 * Logic:
 * 1. Read current build number from lib/build-info.ts
 * 2. Extract date prefix (YYYY.MM.DD) and build count (X)
 * 3. Compare with today's date
 * 4. If date matches, increment X
 * 5. If date doesn't match, reset to YYYY.MM.DD.1
 * 6. Update lib/build-info.ts with new build number
 */

import fs from 'fs';
import path from 'path';

function getTodayDatePrefix(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}.${month}.${day}`;
}

function getFormattedDate(): string {
  const now = new Date();
  const options: Intl.DateTimeFormatOptions = { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  };
  return now.toLocaleDateString('en-US', options);
}

function getCurrentBuildNumber(): string {
  const buildInfoPath = path.join(process.cwd(), 'lib', 'build-info.ts');
  
  if (!fs.existsSync(buildInfoPath)) {
    console.log('⚠️  No existing build-info.ts found. Creating new build number.');
    return '0.0.0.0'; // Will trigger a reset
  }
  
  const content = fs.readFileSync(buildInfoPath, 'utf-8');
  const versionMatch = content.match(/version:\s*'([^']+)'/);
  
  if (!versionMatch) {
    console.log('⚠️  Could not parse existing build number. Creating new build number.');
    return '0.0.0.0';
  }
  
  return versionMatch[1];
}

function generateNewBuildNumber(currentVersion: string): string {
  const todayPrefix = getTodayDatePrefix();
  
  // Parse current version
  const parts = currentVersion.split('.');
  
  if (parts.length !== 4) {
    console.log('⚠️  Invalid build number format. Resetting to today.');
    return `${todayPrefix}.1`;
  }
  
  const [year, month, day, buildCount] = parts;
  const currentDatePrefix = `${year}.${month}.${day}`;
  
  if (currentDatePrefix === todayPrefix) {
    // Same day, increment build count
    const newBuildCount = parseInt(buildCount, 10) + 1;
    console.log(`📅 Same day deployment. Incrementing build count: ${buildCount} → ${newBuildCount}`);
    return `${todayPrefix}.${newBuildCount}`;
  } else {
    // New day, reset to 1
    console.log(`📅 New day deployment. Resetting build count.`);
    console.log(`   Previous: ${currentDatePrefix}.${buildCount}`);
    console.log(`   New:      ${todayPrefix}.1`);
    return `${todayPrefix}.1`;
  }
}

function updateBuildInfoFile(newVersion: string): void {
  const buildInfoPath = path.join(process.cwd(), 'lib', 'build-info.ts');
  const formattedDate = getFormattedDate();
  
  const content = `
/**
 * Build Information
 * Format: YYYY.MM.DD.X (Date + Build Count)
 * 
 * This file is automatically generated by scripts/generate-build-number.ts
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next build
 */

export const BUILD_INFO = {
  version: '${newVersion}',
  date: '${formattedDate}',
  description: 'Automatic build ${newVersion}'
} as const;

export function getBuildVersion(): string {
  return BUILD_INFO.version;
}

export function getFormattedBuildInfo(): string {
  return \`Build \${BUILD_INFO.version}\`;
}
`;
  
  fs.writeFileSync(buildInfoPath, content, 'utf-8');
  console.log(`✅ Updated build-info.ts with version ${newVersion}`);
}

function main() {
  console.log('\n🔧 Automatic Build Number Generator');
  console.log('=====================================\n');
  
  // Get current build number
  const currentVersion = getCurrentBuildNumber();
  console.log(`📋 Current build number: ${currentVersion}`);
  
  // Generate new build number
  const newVersion = generateNewBuildNumber(currentVersion);
  console.log(`🆕 New build number:     ${newVersion}`);
  
  // Update build-info.ts
  updateBuildInfoFile(newVersion);
  
  console.log('\n✨ Build number generation complete!\n');
}

// Run the script
try {
  main();
  process.exit(0);
} catch (error) {
  console.error('\n❌ Error generating build number:', error);
  process.exit(1);
}
